"""Core banking schema."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_core"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("application_users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("supabase_sub", sa.String(128), nullable=False, unique=True), sa.Column("email", sa.String(320)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("roles", sa.Column("id", sa.Integer, primary_key=True), sa.Column("name", sa.String(40), unique=True, nullable=False))
    op.create_table("user_roles", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("application_users.id", ondelete="CASCADE"), primary_key=True), sa.Column("role_id", sa.Integer, sa.ForeignKey("roles.id"), primary_key=True))
    op.create_table("customers", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("application_users.id"), unique=True), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("email", sa.String(320), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("kyc_records", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("document_type", sa.String(40), nullable=False), sa.Column("synthetic_reference", sa.String(80), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="pending"), sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("kyc_reviews", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("kyc_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("kyc_records.id"), nullable=False), sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("application_users.id"), nullable=False), sa.Column("decision", sa.String(24), nullable=False), sa.Column("notes", sa.Text), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("accounts", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("customer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("customers.id"), nullable=False), sa.Column("account_number", sa.String(24), unique=True, nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="active"), sa.Column("balance", sa.Numeric(20, 2), nullable=False, server_default="0", server_onupdate=None), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("balance >= 0", name="ck_accounts_nonnegative"))
    op.create_index("ix_accounts_customer", "accounts", ["customer_id"])
    op.create_table("transfers", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("source_account_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("accounts.id"), nullable=False), sa.Column("destination_account_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("accounts.id"), nullable=False), sa.Column("amount", sa.Numeric(20, 2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("reference", sa.String(160)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("amount > 0"))
    op.create_table("ledger_transactions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("transfer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("transfers.id"), unique=True), sa.Column("description", sa.String(240), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("ledger_entries", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("transaction_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ledger_transactions.id"), nullable=False), sa.Column("account_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("accounts.id"), nullable=False), sa.Column("amount", sa.Numeric(20, 2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("direction", sa.String(8), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.CheckConstraint("amount > 0"), sa.CheckConstraint("direction IN ('debit','credit')"))
    op.create_index("ix_ledger_entries_account_created", "ledger_entries", ["account_id", "created_at"])
    op.create_table("idempotency_keys", sa.Column("key", sa.String(128), primary_key=True), sa.Column("request_hash", sa.String(64), nullable=False), sa.Column("transfer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("transfers.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("audit_logs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("actor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("application_users.id")), sa.Column("action", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(64)), sa.Column("details", postgresql.JSONB, nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))

def downgrade():
    for name in ("audit_logs", "idempotency_keys", "ledger_entries", "ledger_transactions", "transfers", "accounts", "kyc_reviews", "kyc_records", "customers", "user_roles", "roles", "application_users"):
        op.drop_table(name)
